name: Lint

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ruff
        run: pip install ruff

      - name: Ruff Formatter
        run: ruff format --diff .
        env:
          RUFF_OUTPUT_FORMAT: github

      - name: Ruff Linter
        run: ruff check .
        env:
          RUFF_OUTPUT_FORMAT: github

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install mypy
        run: pip install mypy

      - name: mypy
        run: mypy --install-types --non-interactive .
