name: "Validate"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  hassfest:
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"

  # hacs:
  #   name: "HACS Validation"
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: "actions/checkout@v4"
  #
  #     - uses: "hacs/action@main"
  #       with:
  #         category: "integration"
  #         ignore: "brands"
